version: "3.8"

services:
  scit-mcmt:
    container_name: scit-mcmt
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: >
      bash -c "source ~/.bashrc && tail -f /dev/null"
